// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// huber_loss_cpp
double huber_loss_cpp(const arma::mat& R, double tau);
RcppExport SEXP _rrpackrobust_huber_loss_cpp(SEXP RSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(huber_loss_cpp(R, tau));
    return rcpp_result_gen;
END_RCPP
}
// huber_gradient_cpp
arma::mat huber_gradient_cpp(const arma::mat& Y, const arma::mat& X, const arma::mat& B, double tau);
RcppExport SEXP _rrpackrobust_huber_gradient_cpp(SEXP YSEXP, SEXP XSEXP, SEXP BSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(huber_gradient_cpp(Y, X, B, tau));
    return rcpp_result_gen;
END_RCPP
}
// spectral_prox_cpp
List spectral_prox_cpp(const arma::mat& G, double alpha, double lambda, std::string penalty, double a, double gamma, Nullable<int> svd_rank);
RcppExport SEXP _rrpackrobust_spectral_prox_cpp(SEXP GSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP penaltySEXP, SEXP aSEXP, SEXP gammaSEXP, SEXP svd_rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type svd_rank(svd_rankSEXP);
    rcpp_result_gen = Rcpp::wrap(spectral_prox_cpp(G, alpha, lambda, penalty, a, gamma, svd_rank));
    return rcpp_result_gen;
END_RCPP
}
// spectral_norm_sq_over_n_cpp
double spectral_norm_sq_over_n_cpp(const arma::mat& X, int niter);
RcppExport SEXP _rrpackrobust_spectral_norm_sq_over_n_cpp(SEXP XSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(spectral_norm_sq_over_n_cpp(X, niter));
    return rcpp_result_gen;
END_RCPP
}
// proximal_gradient_solver_cpp
List proximal_gradient_solver_cpp(const arma::mat& X, const arma::mat& Y, double tau, double lambda, std::string penalty, double scad_a, double mcp_gamma, Nullable<double> alpha_in, int max_iter, double tol, bool verbose, Nullable<int> svd_rank, Nullable<arma::mat> warm_start);
RcppExport SEXP _rrpackrobust_proximal_gradient_solver_cpp(SEXP XSEXP, SEXP YSEXP, SEXP tauSEXP, SEXP lambdaSEXP, SEXP penaltySEXP, SEXP scad_aSEXP, SEXP mcp_gammaSEXP, SEXP alpha_inSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP svd_rankSEXP, SEXP warm_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type scad_a(scad_aSEXP);
    Rcpp::traits::input_parameter< double >::type mcp_gamma(mcp_gammaSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type alpha_in(alpha_inSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type svd_rank(svd_rankSEXP);
    Rcpp::traits::input_parameter< Nullable<arma::mat> >::type warm_start(warm_startSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_gradient_solver_cpp(X, Y, tau, lambda, penalty, scad_a, mcp_gamma, alpha_in, max_iter, tol, verbose, svd_rank, warm_start));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rrpackrobust_huber_loss_cpp", (DL_FUNC) &_rrpackrobust_huber_loss_cpp, 2},
    {"_rrpackrobust_huber_gradient_cpp", (DL_FUNC) &_rrpackrobust_huber_gradient_cpp, 4},
    {"_rrpackrobust_spectral_prox_cpp", (DL_FUNC) &_rrpackrobust_spectral_prox_cpp, 7},
    {"_rrpackrobust_spectral_norm_sq_over_n_cpp", (DL_FUNC) &_rrpackrobust_spectral_norm_sq_over_n_cpp, 2},
    {"_rrpackrobust_proximal_gradient_solver_cpp", (DL_FUNC) &_rrpackrobust_proximal_gradient_solver_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_rrpackrobust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
