# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

huber_loss_cpp <- function(R, tau) {
    .Call('_rrpackrobust_huber_loss_cpp', PACKAGE = 'rrpackrobust', R, tau)
}

huber_gradient_cpp <- function(Y, X, B, tau) {
    .Call('_rrpackrobust_huber_gradient_cpp', PACKAGE = 'rrpackrobust', Y, X, B, tau)
}

spectral_prox_cpp <- function(G, alpha, lambda, penalty = "SCAD", a = 3.7, gamma = 3.0, svd_rank = NULL) {
    .Call('_rrpackrobust_spectral_prox_cpp', PACKAGE = 'rrpackrobust', G, alpha, lambda, penalty, a, gamma, svd_rank)
}

spectral_norm_sq_over_n_cpp <- function(X, niter = 30L) {
    .Call('_rrpackrobust_spectral_norm_sq_over_n_cpp', PACKAGE = 'rrpackrobust', X, niter)
}

proximal_gradient_solver_cpp <- function(X, Y, tau = 1.0, lambda = 1.0, penalty = "SCAD", scad_a = 3.7, mcp_gamma = 3.0, alpha_in = NULL, max_iter = 2000L, tol = 1e-7, verbose = TRUE, svd_rank = NULL, warm_start = NULL) {
    .Call('_rrpackrobust_proximal_gradient_solver_cpp', PACKAGE = 'rrpackrobust', X, Y, tau, lambda, penalty, scad_a, mcp_gamma, alpha_in, max_iter, tol, verbose, svd_rank, warm_start)
}

